name = "schedule-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "schedule_pro_db"
database_id = "d647746c-e870-44c8-8678-df3152e2fc33"

[vars]
SENDER_EMAIL = "noreply@boluomate.com"
# 以下变量在 Cloudflare Dashboard 或 wrangler secret 中设置：
# JWT_SECRET = "你的随机密钥（至少32位）"
